apiVersion: v1
kind: Service
metadata:
  name:  valaxy-rtp-service
  namespace: valaxy
spec:
  type: NodePort
  selector:
    app: valaxy-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000